method: bayes
metric:
    goal: minimize
    name: test_loss_avg
parameters:
    batch_size:
        values: [128]
    d_model:
        value: 16
    dff:
        values: [128, 256]
    dropout:
        distribution: uniform
        min: 0.05
        max: 0.15
    l_win:
        distribution: int_uniform
        min: 120
        max: 125
    lr: 
        distribution: log_uniform
        min: -6.5
        max: -5.5
    n_epochs: 
        distribution: int_uniform
        min: 60
        max: 100
    n_head: 
        value: 4
    num_layers: 
        distribution: int_uniform
        min: 1
        max: 3
    weight_decay:
        distribution: log_uniform
        min: -6
        max: -4  
    noise_level:
        distribution: uniform
        min: 0.01
        max: 0.05
    embed_dim: 
        value: 16
    result_dir: 
        value: '/home/quang/Documents/XAI_env-main/results/'
    data_dir: 
        value: '/home/quang/Documents/XAI_env-main/data/processed/'
